### ISSUE TITLE
上传后直接删除会不会有数据丢失的风险

### ISSUE THREAD

**Issue by zmyme** [CCSClassBattlecruiser/BiliBiliStreamUploader#1]
`UploadFile(file)
logging.info("delete uploaded file"+file)
print("delete uploaded file"+file)
os.remove(path+'/'+file)`

这一部分感觉好危险，如果前面upload失败了是不是文件就没有了（不过我看了下代码貌似失败了以后会有异常抛出'raise Exception('upload reach max retry times at part {}/{}'.format(chunks_index, chunks_num))'，貌似不会出问题，但是还是感觉好危险（是不是保留最近的几个文件会比较好一些

**Comment by CCSCovenant** [comment]
因为考虑到服务器的硬盘问题所以只能上传完立刻删除~
我会加一个config设置来保留一定数量的replay
