### ISSUE TITLE
将每天的视频分p上传到一个投稿里

### ISSUE THREAD

**Issue by wpcwzy** [CCSClassBattlecruiser/BiliBiliStreamUploader#2]
个人认为可以将每天的视频分p上传到一个投稿里，而不是一个视频一个投稿。投稿太多可能导致粉丝动态里大规模刷屏，对部分粉丝带来影响。

ps 很抱歉因为英语不行，没法发双语issue，可能不便于github社区上的其他国际友人查看，抱歉啦QAQ

**Comment by wpcwzy** [comment]
刚刚又去查阅了一下，bilibiliupload用的是网页api，现在网页无法上传多p了，所以目前实现这个功能可能也有一定难度。
附上网页api无法上传多p的issue链接：https://github.com/comwrg/bilibiliupload/issues/55

**Comment by CCSCovenant** [comment]
嗯 我本来的计划就是上传到一个分p里面 
主要是网页API失效才退而求其次

**Comment by wpcwzy** [comment]
啊最近邮件太多没看到脆脆鲨的回复2333既然已经在计划中了那我就先close掉啦~
感谢！

**Comment by CCSCovenant** [comment]
已经添加了上传到一个分P的功能
